const { roles } = require("../../enums/roles");

let history = [];
let latestCommandAnswer = new Date();

/**
 * This function generates a random role from an array and resets the history if needed.
 * @returns a randomly selected role from an array called "roles". The role is selected using a random
 * number generated by the Math.random() function. The function also checks if the "history" array has
 * reached a length of 4 and resets it if necessary. Finally, the function updates the
 * "latestCommandAnswer" variable with the current date and time.
 */
function smartRandomizeRole(){
    // reset history if more then 10 mins since last time.
    resetHistoryIfNeeded();
    
    // Randoming a number
    let randomNumber = Math.floor(Math.random() * 5) + 1;

    // Random again if already in history list to prevent same role for a person in the same team.
    while(history.includes(roles[randomNumber])) randomNumber = Math.floor(Math.random() * 5) + 1;
    
    // Adding role to history
    history.push(roles[randomNumber])

    // rest the history
    if (history.length == 5) history = [];
    // Setting the Date() for when this action was performed
    latestCommandAnswer = new Date();

    return roles[randomNumber];
}

/**
 * This function resets the history array if the latest command answer is more than 10 minutes apart
 * from the current time.
 */
function resetHistoryIfNeeded() {
    if(isMoreThan10MinutesApart(latestCommandAnswer, new Date())) history = [];
}

/**
 * The function checks if the difference in minutes between two given dates is more than 10.
 * @param date1 - The first date object to compare.
 * @param date2 - The secound date object to compare.
 * @returns a boolean value indicating whether the difference between the two input dates is more than
 * 10 minutes.
 */
function isMoreThan10MinutesApart(date1, date2) {
    const diffInMilliseconds = Math.abs(date1 - date2);
    const diffInMinutes = diffInMilliseconds / (1000 * 60); // convert milliseconds to minutes
    return diffInMinutes > 10;
}

module.exports = {
    smartRandomizeRole,
    roles
}